// backend/insert_demo_cluster_data.js
const { initializeSqlDatabase, closeConnections } = require('./database/connection');
const sql = require('mssql');
const { v4: uuidv4 } = require('uuid');

async function insertDemoData() {
    try {
        console.log('Connecting to database...');
        const pool = await initializeSqlDatabase();

        console.log('Inserting demo clustered alerts...');

        const now = new Date();
        // Create 3 alerts that should cluster together
        // App: "ClusterTestApp", Panel: "ClusterTestPanel"
        // 1. T-30m, duration 2m
        // 2. T-25m, duration 2m (Starts 3m after previous ends -> Gap < 15m)
        // 3. T-20m, duration 2m (Starts 3m after previous ends -> Gap < 15m)

        const baseTime = new Date(now.getTime() - 30 * 60 * 1000); // 30 mins ago

        const alerts = [
            {
                time_fired: new Date(baseTime.getTime()),
                duration_sec: 120, // 2 mins
                message: 'Cluster Test Alert 1'
            },
            {
                time_fired: new Date(baseTime.getTime() + 5 * 60 * 1000), // +5 mins
                duration_sec: 120,
                message: 'Cluster Test Alert 2'
            },
            {
                time_fired: new Date(baseTime.getTime() + 10 * 60 * 1000), // +10 mins
                duration_sec: 120,
                message: 'Cluster Test Alert 3'
            }
        ];

        const app = 'ClusterTestApp';
        const panel = 'ClusterTestPanel';
        const node = 'ClusterNode';

        for (let i = 0; i < alerts.length; i++) {
            const a = alerts[i];
            const timeResolved = new Date(a.time_fired.getTime() + a.duration_sec * 1000);

            const query = `
                INSERT INTO dbo.historicalAlerts (
                    panel_title, application, node_name, 
                    network, object, operator, time_fired, time_resolved, 
                    message, key_field, history_id
                ) VALUES (
                    @panel_title, @application, @node_name,
                    @network, @object, @operator, @time_fired, @time_resolved,
                    @message, @key_field, @history_id
                )
            `;

            const id = uuidv4();
            // incidentNumber is auto-generated by DB (Identity)

            await pool.request()
                // .input('incident_id', sql.VarChar, id) -- Identity!
                .input('panel_title', sql.VarChar, panel)
                .input('application', sql.VarChar, app)
                .input('node_name', sql.VarChar, node)
                .input('network', sql.VarChar, 'TestNetwork')
                .input('object', sql.VarChar, 'TestObject')
                .input('operator', sql.VarChar, 'TestOperator')
                .input('time_fired', sql.DateTime, a.time_fired)
                .input('time_resolved', sql.DateTime, timeResolved)
                // duration_sec is computed
                .input('message', sql.VarChar, a.message)
                .input('key_field', sql.VarChar, 'test_key')
                // incident_number is Identity/Computed?
                .input('history_id', sql.VarChar, uuidv4()) // Required
                .query(query);

            console.log(`Inserted Alert ${i + 1}: ${a.time_fired.toISOString()} (${a.duration_sec}s)`);
        }

        console.log('Done.');

    } catch (err) {
        console.error('Error inserting demo data:', err);
    } finally {
        await closeConnections();
    }
}

insertDemoData();
