// utils/errorTypes.js - Centralized error type definitions
const ERROR = {
  VALIDATION: 'VALIDATION_ERROR',
  DB_CONN: 'DB_CONNECTION_ERROR', 
  DB_QUERY: 'DB_QUERY_ERROR',
  INTERNAL: 'INTERNAL_ERROR',
  PARAMS: 'INVALID_PARAMS',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT: 'RATE_LIMIT_EXCEEDED',
  DATE_RANGE: 'DATE_RANGE_INVALID',
  DURATION: 'DURATION_INVALID'
};

module.exports = { ERROR };